name: Info Metadata on issues
on: 
  issues:
    types: 
      - opened
jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get info
        run: echo "${{ github.action_path }}"
      - name: Repository Name
        run: echo "${{ github.repository }}"

        